common: &common
  adapter: postgresql
  username: going
  password: going_pass

development:
  <<: *common
  database: going_development

test:
  <<: *common
  database: going_test

production:
  <<: *common
  database: going_production